import Head from 'next/head';
import Link from 'next/link';
import style from './../styles/home.module.css';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.container}>
        <Link href={'/posts'} className={style.link}>
          Посты
        </Link>
      </main>
    </>
  );
}
